### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by s1l3nt78** [notkohlrexo/RedEye-Ransomware#1]
Hey so i dont know if your maintaining this but after build and when running, after the laugh plays its shows file not found error of Form1.vb line 61 i think and payload.vb line 8?
Been trying to fix this all day but im not coming right

**Comment by notkohlrexo** [comment]
I'm not updating or giving support to that project anymore, did you fix it tho.?

**Comment by s1l3nt78** [comment]
I havent managed to, but i understand. If i manage to fix it will push the fixes 🙂
